seed: 42
num_steps: 100
decay_rate: 10
defaults:
  - optimizer: adam

hydra:
  mode: MULTIRUN
  launcher:
      setup:
        - export WANDB_MODE=offline
      account: #Add slurm account id here
      cpus_per_task: 8
      mem_gb: 5
      timeout_min: 20
  sweeper:
    params:
      optimizer.lr: 0.001, 0.01, 0.1
      seed: 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30